# Generated by Django 5.2.17 on 2026-09-25 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10)),
                ('files_attempted', models.PositiveIntegerField(default=0)),
                ('files_succeeded', models.PositiveIntegerField(default=0)),
                ('rows_upserted', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('period', models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December'), ('win', 'Winter (Dec-Feb)'), ('spr', 'Spring (Mar-May)'), ('sum', 'Summer (Jun-Aug)'), ('aut', 'Autumn (Sep-Nov)'), ('ann', 'Annual')], max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='climate.ingestionrun')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='climate.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='climate.region')),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'parameter', 'period', 'year'], name='observation_series')],
                'constraints': [models.UniqueConstraint(fields=('region', 'parameter', 'year', 'period'), name='observation_unique_region_parameter_year_period'), models.CheckConstraint(condition=models.Q(('period__in', ('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec', 'win', 'spr', 'sum', 'aut', 'ann'))), name='observation_period_valid')],
            },
        ),
    ]
