# Generated by Django 5.2.17 on 2026-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
